services:
  mysql:
    image: mysql:8.4
    container_name: user-management-mysql

    environment:
      MYSQL_DATABASE: user_management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_ROOT_PASSWORD: rootpassword

    ports:
      - "3306:3306"

    volumes:
      - user_management_mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  user_management_mysql_data:
